[versions]
# Plugins
kotlin = "2.2.21"

ktlint = "13.1.0"

maven-publish = "0.34.0"

# Libs
aws-lambda-java-core = "1.4.0"

kotlinx-serialization = "1.9.0"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }

maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }

[libraries]
aws-lambda-java-core = { group = "com.amazonaws", name = "aws-lambda-java-core", version.ref = "aws-lambda-java-core" }

kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
